import { NetworkJson } from '../../../types';

export const EVM_NETWORKS_JSON: NetworkJson[] = [
  {
    chainId: '1',
    name: 'Ethereum',
    key: 'ethereum',
    active: true,
    chain: '',
    disabled: false,
    providers: {},
    coinGeckoKey: '',
    currentProvider: 'Infura',
    customNodes: [],
    genesisHash: '',
    groups: ['MAIN_NET'],
    ss58Format: 0,
    types: {
      name: '',
      url: '',
    },
    externalApi: {
      history: {
        type: 'ethereum',
        url: 'https://api.etherscan.io/api/',
      },
      explorers: [
        {
          type: 'etherscan',
          types: ['account'],
          url: 'https://api.etherscan.io/api{type}/{value}',
        },
      ],
    },

    assets: [
      {
        isUtility: true,
        id: '887a17c7-1370-4de0-97dd-5422e294fa75dfs',
        name: 'ethereum',
        symbol: 'eth',
        precision: 18,
        priceId: 'ethereum',
        icon: 'https://raw.githubusercontent.com/soramitsu/fearless-utils/master/icons/tokens/coloured/ETH.svg',
        color: 'FF0066',
        staking: 'relaychain',
        purchaseProviders: [],
        type: 'erc20',
      },
      {
        id: '887a17c7-1370-4de0-97dd-5422e294fa75fd',
        name: 'usdt',
        symbol: 'usdt',
        precision: 6,
        smartContract: '0xdAC17F958D2ee523a2206206994597C13D831ec7',
        priceId: 'tether',
        icon: 'https://raw.githubusercontent.com/soramitsu/fearless-utils/master/icons/tokens/coloured/USDT.svg',
        color: 'FF0066',
        staking: 'relaychain',
        purchaseProviders: [],
        type: 'erc20',
      },
    ],
    nodes: [
      {
        url: 'https://mainnet.infura.io/v3/69a249c61c2d469c8695ddf3a9205961',
        name: 'Infura',
      },
    ],
    icon: 'https://raw.githubusercontent.com/soramitsu/fearless-utils/master/icons/chains/white/Polkadot.svg',
    addressPrefix: 0,
    options: ['crowdloans', 'poolStaking'],
  },
  {
    chainId: '5',
    name: 'Ethereum Goerli',
    key: 'ethereum_goerli',
    disabled: false,
    externalApi: {
      explorers: [
        {
          type: 'polkascan',
          types: ['extrinsic', 'account', 'event'],
          url: 'https://polkascan.io/polkadot/{type}/{value}',
        },
      ],
    },
    active: true,
    chain: '',
    providers: {},
    coinGeckoKey: '',
    currentProvider: 'Infura',
    customNodes: [],
    genesisHash: '',
    groups: ['TEST_NET'],
    ss58Format: 0,
    types: {
      name: '',
      url: '',
    },
    assets: [
      {
        isUtility: true,
        id: '887a17c7-1370-4de0-97dd-5422e294fa7fsdfw5',
        name: 'ethereum',
        symbol: 'eth',
        precision: 18,
        priceId: 'ethereum',
        icon: 'https://raw.githubusercontent.com/soramitsu/fearless-utils/master/icons/tokens/coloured/ETH.svg',
        color: 'FF0066',
        staking: 'relaychain',
        purchaseProviders: [],
        type: 'erc20',
      },
      {
        id: '887a17c7-1370-4de0-97dd-5422e294fa7fd5usdc',
        name: 'usdc',
        symbol: 'usdc',
        precision: 6,
        smartContract: '0x07865c6E87B9F70255377e024ace6630C1Eaa37F',
        priceId: 'tether',
        icon: 'https://raw.githubusercontent.com/soramitsu/fearless-utils/master/icons/tokens/coloured/USDC.svg',
        color: 'FF0066',
        staking: 'relaychain',
        purchaseProviders: [],
        type: 'erc20',
      },
      {
        id: '887a17c7-1370-4de0-97dd-5422e294fa7fd5',
        name: 'usdt',
        symbol: 'usdt',
        precision: 6,
        smartContract: '0x509Ee0d083DdF8AC028f2a56731412edD63223B9',
        priceId: 'tether',
        icon: 'https://raw.githubusercontent.com/soramitsu/fearless-utils/master/icons/tokens/coloured/USDT.svg',
        color: 'FF0066',
        staking: 'relaychain',
        purchaseProviders: [],
        type: 'erc20',
      },
    ],
    nodes: [
      {
        url: 'https://goerli.infura.io/v3/69a249c61c2d469c8695ddf3a9205961',
        name: 'Infura Goerli',
      },
    ],
    icon: 'https://raw.githubusercontent.com/soramitsu/fearless-utils/master/icons/chains/white/Polkadot.svg',
    addressPrefix: 0,
    options: ['crowdloans', 'poolStaking'],
  },
];
