import { NetworkJson } from '../../../types';

export const EVM_NETWORKS_JSON: NetworkJson[] = [
  {
    chainId: '1',
    name: 'Ethereum',
    key: 'ethereum',
    active: true,
    chain: '',
    disabled: false,
    providers: {},
    coinGeckoKey: '',
    currentProvider: 'Infura',
    customNodes: [],
    genesisHash: '',
    groups: ['MAIN_NET'],
    ss58Format: 0,
    types: {
      name: '',
      url: '',
    },
    externalApi: {
      explorers: [
        {
          type: 'polkascan',
          types: ['extrinsic', 'account', 'event'],
          url: 'https://polkascan.io/polkadot/{type}/{value}',
        },
      ],
    },
    assets: [
      {
        isUtility: true,
        id: '887a17c7-1370-4de0-97dd-5422e294fa75dfs',
        name: 'ethereum',
        symbol: 'eth',
        precision: 10,
        priceId: 'ethereum',
        icon: 'https://raw.githubusercontent.com/soramitsu/fearless-utils/master/icons/tokens/coloured/ETH.svg',
        color: 'FF0066',
        staking: 'relaychain',
        purchaseProviders: [],
        type: 'erc20',
      },
      {
        id: '887a17c7-1370-4de0-97dd-5422e294fa75fd',
        name: 'usdt',
        symbol: 'usdt',
        precision: 6,
        smartContract: '0x55d398326f99059fF775485246999027B3197955',
        priceId: 'tether',
        icon: 'https://raw.githubusercontent.com/soramitsu/fearless-utils/master/icons/tokens/coloured/USDT.svg',
        color: 'FF0066',
        staking: 'relaychain',
        purchaseProviders: [],
        type: 'erc20',
      },
    ],
    nodes: [
      {
        url: 'wss://eth-mainnet.g.alchemy.com/v2/r2rCN7zWhPZ0cggKYqk_MElwxrrRM4Kw',
        name: 'Infura',
      },
    ],
    icon: 'https://raw.githubusercontent.com/soramitsu/fearless-utils/master/icons/chains/white/Polkadot.svg',
    addressPrefix: 0,
    options: ['crowdloans', 'poolStaking'],
  },
  {
    chainId: '5',
    name: 'Ethereum Goerli',
    key: 'ethereum_goerli',
    disabled: false,
    externalApi: {
      explorers: [
        {
          type: 'polkascan',
          types: ['extrinsic', 'account', 'event'],
          url: 'https://polkascan.io/polkadot/{type}/{value}',
        },
      ],
    },
    active: true,
    chain: '',
    providers: {},
    coinGeckoKey: '',
    currentProvider: 'Infura',
    customNodes: [],
    genesisHash: '',
    groups: ['TEST_NET'],
    ss58Format: 0,
    types: {
      name: '',
      url: '',
    },
    assets: [
      {
        isUtility: true,
        id: '887a17c7-1370-4de0-97dd-5422e294fa7fsdfw5',
        name: 'ethereum',
        symbol: 'eth',
        precision: 10,
        priceId: 'ethereum',
        icon: 'https://raw.githubusercontent.com/soramitsu/fearless-utils/master/icons/tokens/coloured/ETH.svg',
        color: 'FF0066',
        staking: 'relaychain',
        purchaseProviders: [],
        type: 'erc20',
      },
      {
        id: '887a17c7-1370-4de0-97dd-5422e294fa7fd5',
        name: 'usdt',
        symbol: 'usdt',
        precision: 6,
        smartContract: '0x509Ee0d083DdF8AC028f2a56731412edD63223B9',
        priceId: 'tether',
        icon: 'https://raw.githubusercontent.com/soramitsu/fearless-utils/master/icons/tokens/coloured/USDT.svg',
        color: 'FF0066',
        staking: 'relaychain',
        purchaseProviders: [],
        type: 'erc20',
      },
    ],
    nodes: [
      {
        url: 'wss://eth-goerli.g.alchemy.com/v2/WJz4vP6DoqLvRxiJDofxQWq8Fc9UCLbH',
        name: 'Infura Goerli',
      },
    ],
    icon: 'https://raw.githubusercontent.com/soramitsu/fearless-utils/master/icons/chains/white/Polkadot.svg',
    addressPrefix: 0,
    options: ['crowdloans', 'poolStaking'],
  },
];
