name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE (#$NUMBER) - @$AUTHOR'
categories:
  - title: 'Features'
    labels:
      - feature
      - enhancement
  - title: 'Fixes'
    labels:
      - bug
      - fix
  - title: 'Performance'
    labels:
      - perf
      - performance
  - title: 'Tests'
    labels:
      - tests
      - test
  - title: 'Docs & Chore'
    labels:
      - docs
      - chore
      - refactor
version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
      - feature
  patch:
    labels:
      - patch
      - fix
      - bug
  default: patch
template: |
  ## Changes

  $CHANGES
