@Library('jenkins-library')

def buildWithCred  = [
    [$class: 'UsernamePasswordMultiBinding', credentialsId: 'OAUTH_CLIENT_UPLOAD', usernameVariable: 'OAUTH_CLIENT_ID_UPLOAD', passwordVariable: 'OAUTH_CLIENT_SECRET_UPLOAD'],
    [$class: 'UsernamePasswordMultiBinding', credentialsId: 'OAUTH_CLIENT_WEB', usernameVariable: 'OAUTH_CLIENT_ID', passwordVariable: 'OAUTH_CLIENT_SECRET'],
    [$class: 'StringBinding', credentialsId: 'OAUTH_REFRESH_TOKEN', variable: 'OAUTH_REFRESH_TOKEN'],
    [$class: 'StringBinding', credentialsId: 'OAUTH_ITEM_ID', variable: 'OAUTH_ITEM_ID'],
    [$class: 'StringBinding', credentialsId: 'EXTENSION_PUBLIC_KEY', variable: 'EXTENSION_PUBLIC_KEY'],
    [$class: 'StringBinding', credentialsId: 'MOZILLA_API_USER', variable: 'MOZILLA_API_USER'],
    [$class: 'StringBinding', credentialsId: 'MOZILLA_API_TOKEN', variable: 'MOZILLA_API_TOKEN'],
    [$class: 'StringBinding', credentialsId: 'sorabot-github-token', variable: 'GH_TOKEN'],
    [$class: 'StringBinding', credentialsId: 'RAMP_TEST_API_KEY', variable: 'RAMP_TEST_API_KEY'],
    [$class: 'StringBinding', credentialsId: 'RAMP_PROD_API_KEY', variable: 'RAMP_PROD_API_KEY'],
    [$class: 'StringBinding', credentialsId: 'MOONPAY_TEST_API_KEY', variable: 'MOONPAY_TEST_API_KEY'],
    [$class: 'StringBinding', credentialsId: 'MOONPAY_PROD_API_KEY', variable: 'MOONPAY_PROD_API_KEY'],
    [$class: 'StringBinding', credentialsId: 'FL_WEB_ETHERSCAN_API_KEY', variable: 'FL_WEB_ETHERSCAN_API_KEY'],
    [$class: 'StringBinding', credentialsId: 'FL_WEB_BSCSCAN_API_KEY', variable: 'FL_WEB_BSCSCAN_API_KEY'],
    [$class: 'StringBinding', credentialsId: 'FL_WEB_POLYGONSCAN_API_KEY', variable: 'FL_WEB_POLYGONSCAN_API_KEY'],
    [$class: 'StringBinding', credentialsId: 'FL_BLAST_API_ETHEREUM_KEY', variable: 'FL_BLAST_API_ETHEREUM_KEY'],
    [$class: 'StringBinding', credentialsId: 'FL_BLAST_API_BSC_KEY', variable: 'FL_BLAST_API_BSC_KEY'],
    [$class: 'StringBinding', credentialsId: 'FL_BLAST_API_SEPOLIA_KEY', variable: 'FL_BLAST_API_SEPOLIA_KEY'],
    [$class: 'StringBinding', credentialsId: 'FL_BLAST_API_GOERLI_KEY', variable: 'FL_BLAST_API_GOERLI_KEY'],
    [$class: 'StringBinding', credentialsId: 'FL_BLAST_API_POLYGON_KEY', variable: 'FL_BLAST_API_POLYGON_KEY'],
    [$class: 'StringBinding', credentialsId: 'FL_WEB_ALCHEMY_API_ETHEREUM_KEY', variable: 'FL_WEB_ALCHEMY_API_ETHEREUM_KEY'],
    [$class: 'StringBinding', credentialsId: 'FL_BLAST_API_MOONBEAM_KEY', variable: 'FL_BLAST_API_MOONBEAM_KEY'],
    [$class: 'StringBinding', credentialsId: 'FL_BLAST_API_MOONRIVER_KEY', variable: 'FL_BLAST_API_MOONRIVER_KEY'],
    [$class: 'StringBinding', credentialsId: 'FL_BLAST_API_OKTC_MAINNET_KEY', variable: 'FL_BLAST_API_OKTC_MAINNET_KEY'],
    [$class: 'StringBinding', credentialsId: 'FL_BLAST_API_OPTIMISM_MAINNET_KEY', variable: 'FL_BLAST_API_OPTIMISM_MAINNET_KEY'],
    [$class: 'StringBinding', credentialsId: 'FL_WEB_OPTIMISTIC_ETHERSCAN_API_KEY', variable: 'FL_WEB_OPTIMISTIC_ETHERSCAN_API_KEY'],
    [$class: 'StringBinding', credentialsId: 'FL_WEB_ARBISCAN_API_KEY', variable: 'FL_WEB_ARBISCAN_API_KEY'],
    [$class: 'StringBinding', credentialsId: 'FL_WEB_SNOWTRACE_API_KEY', variable: 'FL_WEB_SNOWTRACE_API_KEY'],
    [$class: 'StringBinding', credentialsId: 'FL_WEB_ZKEVM_POLYGONSCAN_API_KEY', variable: 'FL_WEB_ZKEVM_POLYGONSCAN_API_KEY'],
    [$class: 'StringBinding', credentialsId: 'FL_OKLINK_API_KEY', variable: 'VUE_APP_FL_WEB_X1_TESTNET_API_KEY'],
    [$class: 'StringBinding', credentialsId: 'FL_WEB_TON_API_KEY', variable: 'FL_WEB_TON_API_KEY'],
    [$class: 'StringBinding', credentialsId: 'FL_WEB_DWELLIR_API_KEY', variable: 'FL_DWELLIR_API_KEY']
]


def pipeline = new org.js.AppArtifactsPipeline(
    steps:                      this,
    secretScannerExclusion:     '/src/extension/background/extension-base/src/api/evm/history.ts',
    buildCmds:                  ['yarn build:extension:all'],
    nexusCredential:            'bot-fearless-rw',
    nexusProjectPath:           'fearless/extension',
    nexusNotification:           true,
    nexusChatID:                "-1001934877683",
    sonarProjectKey:            'fearless:fearless-wallet-web',
    sonarProjectName:           'fearless-wallet-web',
    sonarCredential:            'sonar_fearless_token',
    extSlug:                    'fearless-wallet',
    mozillaChannel:             'listed',
    distFolders:                ['./dist/extension/firefox','./dist/extension/chrome'],
    distFoldersTestNets:        ['./dist/extension/chrome-test'],
    preBuildCmds:               ['apt-get update && apt-get install zip jq -y && corepack enable &&yarn set version 3.4.1 && yarn install'],
    nexusFiles:                 [ '.zip'],
    chromeExtFile:              'fearless-wallet-extension-chrome.zip',
    mozillaExtFile:             'fearless-wallet-extension-firefox.zip',
    uploadToNexusFor:           ['master','develop','stage'],
    uploadToGoogleFor:          ['master'],
    uploadToFirefoxFor:         ['master'],
    buildWithCred:              buildWithCred,
    dojoProductType:            'fearless-web',
    sonarSrcPath:               'src',
    sonarTestsPath:             'tests',
    checkSquashCommits:         true,
    triggerAutotest:            true,
    downstreamJob:              '/qa/soramitsu-test-framework/fearless-wallet-web',
    downstreamJobParams:        [
        [$class: 'StringParameterValue', name: 'targetBranch', value: env.BRANCH_NAME],
        [$class: 'StringParameterValue', name: 'typeTest', value: 'tests:fearless-smoke']
    ],
    dockerImageName:            'fearless/wallet-web',
    dockerRegistryCred:         'bot-fearless-rw',
    buildDockerImage:           'build-tools/node:20-alpine',
    webPreBuildCmds:            ['corepack enable && yarn set version 3.4.1 && yarn install'],
    k8sPrDeploy:                true,
    vaultPrPath:                "argocd-cc/src/charts/fearless/wallet-web/environments/tachi/",
    vaultUser:                  "fearless-rw",
    vaultCredId:                "fearlessVaultCreds",
    valuesDestPath:             "argocd-cc/src/charts/fearless/wallet-web/",
    devValuesPath:              "dev/dev/",
    initialSecretName:          "fearless-dev-wallet-web-wallet-web-web-eso-base",
    initialNameSpace:           "fearless-dev-web",
    targetNameSpace:            "fearless-${env.CHANGE_ID}-web",
    targetSecretName:           "fearless-${env.CHANGE_ID}-wallet-web-pr-wallet-web-eso-base"
)
pipeline.runPipeline()