import type { SelectionValidator, MyValidator } from '@/interfaces';

export const validators: SelectionValidator[] = [
  {
    name: 'Agustín trabajo',
    address: '5E2ku91ffpVpz78WNwP18ZxR2ComiB9KLQqWnEd6UCS2f3m3',
    description: 'test',
    isSelect: false,
    isRecommended: true,
    isSlashed: false,
    isOversubscribed: true,
    limitValidatorsIdentity: true,
    onchainIdentity: true,
    apy: 12.8,
  },
  {
    name: 'Cristela Estilista',
    address: '5GecoStYi2bHzKz6LwE2LWa8MWJxaZYAGjx2WeH8r4RTnQ6e',
    description: 'test',
    isSelect: false,
    isRecommended: true,
    isSlashed: false,
    isOversubscribed: false,
    limitValidatorsIdentity: false,
    onchainIdentity: true,
    apy: 11.1,
  },
  {
    name: 'Tia Jaquelín',
    address: '5GLDeyxgNzsnm4NeSHZd9imbSMaV2RUPGRSkchxsUqSbfBpu',
    description: 'test',
    isSelect: false,
    isSlashed: true,
    isOversubscribed: false,
    limitValidatorsIdentity: false,
    onchainIdentity: false,
    apy: 5.2,
  },
  {
    name: 'Dentista Aguilda',
    address: '5DfE4cSm5Vmndx96vByJ18DzxMWvagxtHBiadCpGefrGQfJ6',
    description: 'test',
    isSelect: false,
    isSlashed: true,
    isOversubscribed: true,
    limitValidatorsIdentity: true,
    onchainIdentity: false,
    apy: 23.1,
  },
  {
    name: 'Dentista Aguilda',
    address: '5Cybd5gdyFrfSzx5n9XViH71eoxYGJLKoseY762Mu7yfQa6d',
    description: 'test',
    isSelect: false,
    isSlashed: true,
    isOversubscribed: false,
    limitValidatorsIdentity: false,
    onchainIdentity: true,
    apy: 49.1,
  },
  {
    name: 'Denya Contadora',
    address: '5EAJh2UwK4u1RiZTH2zc5yRtcyUvkcpBakj6UDJHCT9rnoK8',
    description: 'test',
    isSelect: false,
    isSlashed: true,
    isOversubscribed: false,
    limitValidatorsIdentity: false,
    onchainIdentity: true,
    apy: 43.5,
  },
  {
    name: 'Fearless Web Extension',
    address: '5HHMCzs1PGci5MNVbght7EjC3vZP58EPcQM3CEassbRsAtKc',
    description: 'test',
    isSelect: false,
    isSlashed: false,
    isOversubscribed: false,
    limitValidatorsIdentity: true,
    onchainIdentity: true,
    apy: 99.9,
  },
];

export const myValidators: MyValidator[] = [
  {
    name: 'Agustín trabajo',
    address: '5E2ku91ffpVpz78WNwP18ZxR2ComiB9KLQqWnEd6UCS2f3m3',
    description: 'test',
    rewards: '1.1',
    isRecommended: true,
    isSlashed: false,
    isOversubscribed: true,
    limitValidatorsIdentity: true,
    onchainIdentity: true,
    apy: 12.8,
  },
  {
    name: 'Agustín Contadora',
    address: '5EAJh2UwK4u1RiZTH2zc5yRtcyUvkcpBakj6UDJHCT9rnoK8',
    description: 'test',
    rewards: '2.16',
    isRecommended: true,
    isSlashed: false,
    isOversubscribed: true,
    limitValidatorsIdentity: true,
    onchainIdentity: false,
    apy: 15.1,
  },
];
