import { ContractType } from '@/interfaces/ether';

const ETHEREUM_NETWORKS = ['moonbeam', 'moonriver', 'moonbase alpha', 'astarEvm', 'shidenEvm'];
const NOT_SUPPORTED_ALL_TRANSFER_NETWORKS = ['karura', 'acala', 'acala_testnet'];

const RELAY_CHAINS = ['polkadot', 'kusama', 'westend', 'rococo'];
const NATIVE_PARACHAINS = ['statemint', 'statemine', 'encointer on kusama', 'westmint', 'rockmine'];
const NATIVE_NETWORKS = [...RELAY_CHAINS, ...NATIVE_PARACHAINS];

const NOT_SUPPORTED_SUBQUERY_NETWORKS = [
  'kico',
  'phala',
  'khala',
  'unique',
  'quartz',
  'kabocha',
  'efinity',
  'litentry',
  'basilisk',
  'parallel',
  'moonriver',
  'centrifuge',
  'imbue kusama',
  'parallel heiko',
  'pichiu network',
  'integritee shell',
  'composable finance',
  'dorafactory network',
  'datahighway tanganika',
  'invArch tinker network',
];

const MAIN_NETWORKS: Record<string, string> = {
  dot: 'polkadot',
  ksm: 'kusama',
  wnd: 'westend',
  roc: 'rococo',
};

const ETHEREUM_ADDRESS_LENGTH = 42;
const ETHEREUM_ADDRESS_PREFIX = '0x';
const AUTO_CONNECT_MS = 3000;
const MAX_CONTINUE_RETRY = 3;

const WESTEND_GENESISHASH = '0xe143f23803ac50e8f6f8e62695d1ce9e4e1d68aa36c1cd2cfd15340213f3423e';
const MOONBEAM_GENESISHASH = '0xfe58ea77779b7abda7da4ec526d14db9b1e9cd40a217c34892af80a9b332b76d';

const NETWORK_AND_ASSET: Record<string, string> = {
  statemine: 'statemine',
  statemint: 'statemine',
  kico: 'kico',
  'encointer on kusama': 'encointer',
  westend: 'westend',
  wnd: 'westend',
  acala: 'acala',
  aca: 'acala',
  karura: 'karura',
  kar: 'karura',
  moonriver: 'moonriver',
  movr: 'moonriver',
  shiden: 'shiden',
  sdn: 'shiden',
  bifrost: 'bifrost',
  'bifrost polkadot': 'bifrost',
  bnc: 'bifrost',
  'kilt spiritnet': 'kilt_spiritnet',
  kilt: 'kilt_spiritnet',
  calamari: 'calamari',
  kma: 'calamari',
  quartz: 'quartz',
  qtz: 'quartz',
  'parallel heiko': 'parallelfinance',
  hko: 'parallelfinance',
  picasso: 'picasso',
  pica: 'picasso',
  altair: 'altair',
  air: 'altair',
  'bit.country pioneer': 'bitcountry',
  neer: 'bitcountry',
  clover: 'clover',
  clv: 'clover',
  astar: 'astar',
  astr: 'astar',
  parallel: 'parallelfinance',
  para: 'parallelfinance',
  basilisk: 'basilisk',
  bsx: 'basilisk',
  moonbeam: 'moonbeam',
  glmr: 'moonbeam',
  'moonbase alpha': 'moonbase_alpha',
  dev: 'moonbase_alpha',
  genshiro: 'genshiro',
  gens: 'genshiro',
  robonomics: 'robonomics',
  xrt: 'robonomics',
  kintsugi: 'kintsugi',
  kint: 'kintsugi',
  subsocial: 'subsocial',
  sub: 'subsocial',
  zeitgeist: 'zeitgeist',
  ztg: 'zeitgeist',
  'integritee shell': 'integritee',
  teer: 'integritee',
  hydradx: 'hydradx',
  hdx: 'hydradx',
  centrifuge: 'centrifuge',
  cfg: 'centrifuge',
  efinity: 'efinity',
  efi: 'efinity',
  'polkadex main network': 'polkadex',
  pdex: 'polkadex',
  'turing network': 'turing',
  tur: 'turing',
  'crust shadow parachain': 'crustshadow',
  csm: 'crustshadow',
  interlay: 'interlay',
  intr: 'interlay',
  'dorafactory network': 'dora_factory',
  dora: 'dora_factory',
  unique: 'unique',
  unq: 'unique',
  'origintrail parachain': 'origintrail',
  otp: 'origintrail',
  'nodle parachain': 'nodle',
  nodl: 'nodle',
  'sora kusama': 'sora',
  xor: 'sora',
  'composable finance': 'composable',
  layr: 'composable',
  'crab parachain': 'crab',
  crab: 'crab',
  kabocha: 'kabocha',
  kab: 'kabocha',
  'pichiu network': 'pichiu',
  pchu: 'pichiu',
  equilibrium: 'equilibrium',
  eq: 'equilibrium',
  'datahighway tanganika': 'datahighway',
  dhx: 'datahighway',
  'gm parachain': 'gm_parachain',
  fren: 'gm_parachain',
  'bajun kusama': 'bajun',
  baju: 'bajun',
  'imbue kusama': 'imbue',
  imbu: 'imbue',
  'invarch tinker network': 'tinker',
  tnkr: 'tinker',
  'mangata kusama mainnet': 'mangata',
  mgx: 'mangata',
  amplitude: 'amplitude',
  ampe: 'amplitude',
  'darwinia parachain': 'darwinia',
  ring: 'darwinia',
  'kylin network': 'kylin network',
  kyl: 'kylin network',
  polkadot: 'polkadot',
  'polkadot (test)': 'polkadot',
  dot: 'polkadot',
  kusama: 'kusama',
  'kusama (test)': 'kusama',
  ksm: 'kusama',
  litentry: 'litentry',
  litmus: 'litmus',
  phala: 'phala',
  khala: 'khala',
  'sora test': 'sora',
  'sora mainnet': 'sora',
  'snow kusama': 'snow',
  icz: 'snow',
};

const PHA: Record<string, string> = {
  polkadot: 'phala',
  kusama: 'khala',
};

const LIT: Record<string, string> = {
  polkadot: 'litentry',
  kusama: 'litmus',
};

const UNIT: Record<string, string> = {
  'polkadot (test)': 'polkadot',
  'kusama (test)': 'kusama',
};

const ETH_BLOCK_EXPLORER: Record<string, string> = {
  // moonbeam: 'https://moonbeam.moonscan.io',
  // moonriver: 'https://moonriver.moonscan.io',
  // moonbase: 'https://moonbase.moonscan.io',
  ethereum: 'https://etherscan.io',
  // ethereum_goerli: 'https://goerli.etherscan.io',
  // binance: 'https://bscscan.com',
  // binance_test: 'https://testnet.bscscan.com',
};
const PREDEFINED_NETWORKS = {
  ethereum: {
    key: 'ethereum',
    chain: 'Ethereum Mainnet',
    genesisHash: '0xb60d7bdd334cd3768d43f14a05c7fe7e886ba5bcb77e1064530052fed1a3f145',
    ss58Format: 0,
    providers: {
      Cloudflare: 'https://cloudflare-eth.com',
      BlastApi: 'https://eth-mainnet.public.blastapi.io',
      Infura: 'https://mainnet.infura.io/v3/b6bf7d3508c941499b10025c0776eaf8',
    },
    active: false,
    currentProviderMode: 'http',
    currentProvider: 'Infura',
    groups: ['MAIN_NET'],
    isEthereum: true,
    nativeToken: 'ETH',
    decimals: 18,
    coinGeckoKey: 'ethereum',
    evmChainId: 1,
    supportBonding: false,
    getStakingOnChain: false,
    abiExplorer: 'https://etherscan.io',
    supportSmartContract: [ContractType.evm],
  },
};
export {
  UNIT,
  LIT,
  PHA,
  ETH_BLOCK_EXPLORER,
  NETWORK_AND_ASSET,
  PREDEFINED_NETWORKS,
  RELAY_CHAINS,
  MAIN_NETWORKS,
  NATIVE_NETWORKS,
  AUTO_CONNECT_MS,
  NATIVE_PARACHAINS,
  ETHEREUM_NETWORKS,
  ETHEREUM_ADDRESS_PREFIX,
  ETHEREUM_ADDRESS_LENGTH,
  MAX_CONTINUE_RETRY,
  NOT_SUPPORTED_SUBQUERY_NETWORKS,
  NOT_SUPPORTED_ALL_TRANSFER_NETWORKS,
  WESTEND_GENESISHASH,
  MOONBEAM_GENESISHASH,
};
