const ETHEREUM_NETWORKS = ['moonbeam', 'moonriver', 'moonbase alpha', 'astarEvm', 'shidenEvm'];
const NOT_SUPPORTED_ALL_TRANSFER_NETWORKS = ['karura', 'acala', 'acala_testnet'];

const RELAY_CHAINS = ['polkadot', 'kusama', 'westend', 'rococo'];
const NATIVE_PARACHAINS = ['statemint', 'statemine', 'encointer on kusama', 'westmint', 'rockmine'];
const NATIVE_NETWORKS = [...RELAY_CHAINS, ...NATIVE_PARACHAINS];

const NOT_SUPPORTED_SUBQUERY_NETWORKS = [
  'kico',
  'phala',
  'khala',
  'unique',
  'quartz',
  'kabocha',
  'efinity',
  'litentry',
  'basilisk',
  'parallel',
  'moonriver',
  'centrifuge',
  'imbue kusama',
  'parallel heiko',
  'pichiu network',
  'integritee shell',
  'composable finance',
  'dorafactory network',
  'datahighway tanganika',
  'invArch tinker network',
];

const MAIN_NETWORKS: Record<string, string> = {
  dot: 'polkadot',
  ksm: 'kusama',
  wnd: 'westend',
  roc: 'rococo',
};

const ETHEREUM_ADDRESS_LENGTH = 42;
const ETHEREUM_ADDRESS_PREFIX = '0x';
const AUTO_CONNECT_MS = 3000;
const MAX_CONTINUE_RETRY = 1;

const WESTEND_GENESISHASH = '0xe143f23803ac50e8f6f8e62695d1ce9e4e1d68aa36c1cd2cfd15340213f3423e';
const MOONBEAM_GENESISHASH = '0xfe58ea77779b7abda7da4ec526d14db9b1e9cd40a217c34892af80a9b332b76d';

const NETWORK_AND_ASSET: Record<string, string> = {
  statemine: 'Statemine',
  statemint: 'Statemine',
  kico: 'KICO',
  'encointer on kusama': 'encointer',
  westend: 'Westend',
  wnd: 'wnd',
  acala: 'acala',
  aca: 'aca',
  karura: 'Karura',
  kar: 'kar',
  moonriver: 'Moonriver',
  movr: 'movr',
  shiden: 'Shiden',
  sdn: 'sdn',
  bifrost: 'Bifrost',
  'bifrost polkadot': 'Bifrost',
  bnc: 'bnc',
  'kilt spiritnet': 'kilt',
  kilt: 'kilt',
  calamari: 'Calamari',
  kma: 'kma',
  quartz: 'quartz',
  qtz: 'qtz',
  'parallel heiko': 'parallelfinance',
  hko: 'parallelfinance',
  picasso: 'picasso',
  pica: 'pica',
  altair: 'Altair',
  air: 'air',
  'bit.country pioneer': 'bitcountry',
  neer: 'neer',
  clover: 'clover',
  clv: 'clv',
  astar: 'astar',
  astr: 'astr',
  parallel: 'parallelfinance',
  para: 'para',
  basilisk: 'Basilisk',
  bsx: 'bsx',
  moonbeam: 'Moonbeam',
  glmr: 'glmr',
  'moonbase alpha': 'Moonbeam',
  dev: 'moonbase_alpha',
  genshiro: 'Genshiro',
  gens: 'gens',
  azero: 'azero',
  robonomics: 'robonomics',
  xrt: 'xrt',
  kintsugi: 'kintsugi',
  kint: 'kint',
  subsocial: 'subsocial_new',
  sub: 'sub',
  zeitgeist: 'zeitgeist',
  ztg: 'ztg',
  'integritee shell': 'integritee',
  teer: 'teer',
  hydradx: 'hydradx',
  hdx: 'hdx',
  centrifuge: 'centrifuge',
  cfg: 'cfg',
  efinity: 'efinity',
  efi: 'efi',
  'polkadex main network': 'polkadex',
  pdex: 'pdex',
  'turing network': 'OAK',
  tur: 'tur',
  'crust shadow parachain': 'crustshadow',
  csm: 'CSM_Crust_Shadow',
  interlay: 'interlay',
  intr: 'intr',
  'dorafactory network': 'DoraFactory',
  dora: 'dora',
  unique: 'unique',
  unq: 'unq',
  'origintrail parachain': 'OriginTrail',
  otp: 'otp',
  'nodle parachain': 'nodle',
  nodl: 'nodl',
  'sora kusama': 'SORA',
  xor: 'xor',
  'composable finance': 'composable',
  layr: 'layr',
  'crab parachain': 'crab',
  crab: 'crab',
  kabocha: 'Kabocha',
  kab: 'kab',
  'pichiu network': 'Pichiu',
  pchu: 'pchu',
  equilibrium: 'equilibrium',
  eq: 'eq',
  'datahighway tanganika': 'DataHighway',
  dhx: 'dhx',
  'gm parachain': 'GM Parachain',
  fren: 'fren',
  'bajun kusama': 'Bajun',
  baju: 'baju',
  'imbue kusama': 'Imbue',
  imbu: 'imbu',
  'invarch tinker network': 'Tinkernet',
  tnkr: 'tnkr',
  'mangata kusama mainnet': 'MagnataX',
  mgx: 'mgx',
  amplitude: 'Amplitude',
  ampe: 'ampe',
  'darwinia parachain': 'darwinia',
  darwinia: 'darwinia',
  ring: 'ring',
  'kylin network': 'Kylin Network',
  kyl: 'kyl',
  polkadot: 'Polkadot',
  'polkadot (test)': 'Polkadot',
  dot: 'dot',
  kusama: 'Kusama',
  'kusama (test)': 'Kusama',
  ksm: 'ksm',
  litentry: 'litentry',
  litmus: 'litmus',
  phala: 'phala',
  khala: 'Khala',
  'sora test': 'SORA',
  'sora mainnet': 'SORA',
  'snow kusama': 'SNOW',
  icz: 'icz',
};

const PHA: Record<string, string> = {
  polkadot: 'pha',
  kusama: 'pha',
};

const LIT: Record<string, string> = {
  polkadot: 'lit_dot',
  kusama: 'lit_ksm',
};

const UNIT: Record<string, string> = {
  'polkadot (test)': 'DOT',
  'kusama (test)': 'KSM',
};

export {
  UNIT,
  LIT,
  PHA,
  NETWORK_AND_ASSET,
  RELAY_CHAINS,
  MAIN_NETWORKS,
  NATIVE_NETWORKS,
  AUTO_CONNECT_MS,
  NATIVE_PARACHAINS,
  ETHEREUM_NETWORKS,
  ETHEREUM_ADDRESS_PREFIX,
  ETHEREUM_ADDRESS_LENGTH,
  MAX_CONTINUE_RETRY,
  NOT_SUPPORTED_SUBQUERY_NETWORKS,
  NOT_SUPPORTED_ALL_TRANSFER_NETWORKS,
  WESTEND_GENESISHASH,
  MOONBEAM_GENESISHASH,
};
