export const SubNetworkId = {
  Mainnet: 'Mainnet',
  Polkadot: 'Polkadot',
  PolkadotSora: 'PolkadotSora',
  PolkadotAcala: 'PolkadotAcala',
  PolkadotAssetHub: 'PolkadotAssetHub',
  PolkadotAstar: 'PolkadotAstar',
  PolkadotMoonbeam: 'PolkadotMoonbeam',
  Kusama: 'Kusama',
  KusamaSora: 'KusamaSora',
  KusamaAssetHub: 'KusamaAssetHub',
  KusamaCurio: 'KusamaCurio',
  KusamaShiden: 'KusamaShiden',
  Rococo: 'Rococo',
  RococoSora: 'RococoSora',
  Alphanet: 'Alphanet',
  AlphanetSora: 'AlphanetSora',
  AlphanetMoonbase: 'AlphanetMoonbase',
  Liberland: 'Liberland',
  Custom: 'Custom',
} as const;
