import { MIN1 } from '@/consts/time';

const EXTENSION_PREFIX = 'fw';

const PORT_PREFIX = `${EXTENSION_PREFIX}-fearless`;

const PORT_CONTENT = `${PORT_PREFIX}-content`;
const PORT_EXTENSION = `${PORT_PREFIX}-extension`;
const MESSAGE_ORIGIN_PAGE = `${PORT_PREFIX}-page`;
const MESSAGE_ORIGIN_CONTENT = `${PORT_PREFIX}-content`;

const PASSWORD_EXPIRY_MIN = 15;
const PASSWORD_EXPIRY_MS = PASSWORD_EXPIRY_MIN * MIN1;

export {
  PASSWORD_EXPIRY_MIN,
  PASSWORD_EXPIRY_MS,
  EXTENSION_PREFIX,
  PORT_CONTENT,
  PORT_EXTENSION,
  MESSAGE_ORIGIN_PAGE,
  MESSAGE_ORIGIN_CONTENT,
};
